import type { TutorialItem } from "../types";

export const UBICACIONES_ITEMS: TutorialItem[] = [
  {
    id: "crear-ubicacion",
    title: "¿Cómo crear una ubicación (ambiente/salón)?",
    description:
      "Ve a Ubicaciones y crea un ambiente. Los tickets prestan ubicaciones.",
    flow: {
      title: "Crear ubicación",
      steps: [
        {
          id: "howto-crear-ubicacion-1",
          route: "/ubicaciones",
          selector: '[data-tour="ubicaciones-create-button"]',
          title: "Abrir el formulario",
          description: "Haz clic en “Crear” para abrir el formulario en un modal.",
          autoAdvanceOnClick: true,
          side: "left",
          align: "end",
        },
        {
          id: "howto-crear-ubicacion-2",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-codigo"]',
          title: "Código",
          description: "Escribe el código del ambiente (ej: SAL-02).",
          beforeClickSelector: '[data-tour="ubicaciones-create-button"]',
          side: "bottom",
          align: "start",
        },
        {
          id: "howto-crear-ubicacion-3",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-nombre"]',
          title: "Nombre",
          description: "Escribe el nombre del ambiente (ej: Sala de Sistemas 2).",
          side: "bottom",
          align: "start",
        },
        {
          id: "howto-crear-ubicacion-4",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-sede"]',
          title: "Sede",
          description: "Selecciona la sede donde existe esta ubicación.",
          side: "bottom",
          align: "start",
        },
        {
          id: "howto-crear-ubicacion-5",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-submit"]',
          title: "Guardar",
          description: "Pulsa “Crear” para guardar la ubicación.",
          autoAdvanceOnGone: true,
          autoAdvanceGoneSelector: '[data-tour="ubicacion-form"]',
          side: "top",
          align: "end",
        },
        {
          id: "howto-crear-ubicacion-6",
          route: "/ubicaciones",
          selector: '[data-tour="page-title"]',
          title: "Verificación",
          description:
            "Verifica que la ubicación aparezca en la tabla. Si no la ves, revisa el buscador o recarga la lista.",
          side: "bottom",
          align: "start",
        },
      ],
    },
  },
  {
    id: "editar-ubicacion",
    title: "¿Cómo editar una ubicación?",
    description: "En la tabla, usa el botón Editar.",
    flow: {
      title: "Editar ubicación",
      steps: [
        {
          id: "howto-editar-ubicacion-1",
          route: "/ubicaciones",
          selector: '[data-tour="ubicaciones-edit-first"]',
          title: "Abrir la edición",
          description: "Haz clic en “Editar” para abrir el formulario en un modal.",
          autoAdvanceOnClick: true,
          side: "left",
          align: "end",
        },
        {
          id: "howto-editar-ubicacion-2",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-codigo"]',
          title: "Actualizar el código",
          description: "Ajusta el código si cambió (ej: SAL-02).",
          beforeClickSelector: '[data-tour="ubicaciones-edit-first"]',
          side: "bottom",
          align: "start",
        },
        {
          id: "howto-editar-ubicacion-3",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-sede"]',
          title: "Verificar sede",
          description: "Confirma que la ubicación está asociada a la sede correcta.",
          side: "bottom",
          align: "start",
        },
        {
          id: "howto-editar-ubicacion-4",
          route: "/ubicaciones",
          selector: '[data-tour="ubicacion-form-submit"]',
          title: "Guardar cambios",
          description: "Pulsa “Guardar cambios” para actualizar la ubicación.",
          side: "top",
          align: "end",
        },
      ],
    },
  },
  {
    id: "eliminar-ubicacion",
    title: "¿Cómo eliminar una ubicación?",
    description: "En la tabla, usa el botón Eliminar.",
    flow: {
      title: "Eliminar ubicación",
      steps: [
        {
          id: "howto-eliminar-ubicacion-1",
          route: "/ubicaciones",
          selector: '[data-tour="ubicaciones-delete-first-trigger"]',
          title: "Iniciar eliminación",
          description: "Haz clic en “Eliminar” para abrir la confirmación.",
          autoAdvanceOnClick: true,
          side: "left",
          align: "end",
        },
        {
          id: "howto-eliminar-ubicacion-2",
          route: "/ubicaciones",
          selector: '[data-tour="ubicaciones-delete-first-confirm"]',
          title: "Confirmar",
          description: "Pulsa “Sí, eliminar” para confirmar la eliminación.",
          autoAdvanceOnClick: true,
          side: "top",
          align: "end",
        },
        {
          id: "howto-eliminar-ubicacion-3",
          route: "/ubicaciones",
          selector: '[data-tour="page-title"]',
          title: "Listo",
          description: "La ubicación fue eliminada.",
          side: "bottom",
          align: "start",
        },
      ],
    },
  },
];

